#!/usr/bin/env node
/**
 * Regenerates src/chain/abis.ts from the compiled forge artifacts in out/.
 *
 * This exists because hand-transcribing ABIs from reading contracts/*.sol
 * drifts silently the moment the Solidity changes — exactly what happened
 * once before here. The compiled artifact is the only source of truth, so
 * this script reads it mechanically instead of anyone re-typing it.
 *
 * Usage:
 *   export PATH="$HOME/.foundry/bin:$PATH"
 *   forge build          # refresh out/ from the current contracts/
 *   npm run abis         # regenerate src/chain/abis.ts from out/
 *
 * Run this after ANY change to contracts/*.sol, and commit the result.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(rootDir, 'out');
const targetFile = path.join(rootDir, 'src', 'chain', 'abis.ts');

// contract name (matches contracts/<name>.sol and out/<name>.sol/<name>.json) -> exported const name
const CONTRACTS = [
  { name: 'KarmaRune', exportName: 'karmaRuneAbi' },
  { name: 'KarmaDex', exportName: 'karmaDexAbi' },
  { name: 'KarmaShard', exportName: 'karmaShardAbi' },
  { name: 'Staking', exportName: 'stakingAbi' },
  { name: 'Treasury', exportName: 'treasuryAbi' },
];

function loadAbi(contractName) {
  const artifactPath = path.join(outDir, `${contractName}.sol`, `${contractName}.json`);
  if (!existsSync(artifactPath)) {
    throw new Error(
      `generate-abis: missing forge artifact at ${artifactPath}. Run "forge build" first.`
    );
  }
  const artifact = JSON.parse(readFileSync(artifactPath, 'utf8'));
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`generate-abis: ${artifactPath} has no "abi" array`);
  }
  return artifact.abi;
}

const sections = CONTRACTS.map(({ name, exportName }) => {
  const abi = loadAbi(name);
  return `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;`;
});

const header = `/**
 * Contract ABIs for viem clients.
 *
 * GENERATED FILE — do not hand-edit. Source of truth is the compiled forge
 * artifacts in out/<Contract>.sol/<Contract>.json (built from contracts/*.sol).
 * Regenerate after any contract change:
 *
 *   export PATH="$HOME/.foundry/bin:$PATH"
 *   forge build
 *   npm run abis
 *
 * Generated by scripts/generate-abis.mjs.
 */
`;

const output = `${header}\n${sections.join('\n\n')}\n`;
writeFileSync(targetFile, output);

console.log(`generate-abis: wrote ${path.relative(rootDir, targetFile)} from ${CONTRACTS.length} artifacts:`);
for (const { name, exportName } of CONTRACTS) {
  console.log(`  - ${name} -> ${exportName}`);
}
